services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduflex
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/eduflex
      REDIS_URL: redis://redis:6379
      # Add other environment variables as needed
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  prisma-studio:
    build: ./server
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/eduflex
    ports:
      - "5555:5555"
    depends_on:
      - db
    command: npx prisma studio --hostname 0.0.0.0

volumes:
  redis_data:
  db_data:
